# Lab01 - Getting Started

Name: Jimmy (Qixiao) Zhu
Class: CSCI 349 - Intro to Data Mining
Semester: 2023SP
Instructor: Brian King

**2.** [M] Did you read the syllabus? All of it? Do you understand and agree to abide by the cheating rules? Write a
sentence clearly indicating your commitment to not cheating.

I have read the syllabus and understand and agree to abide by the cheating rules. I promise I will not cheat.

**3.** [M] What are you hoping to get out of this course?

I hope to learn a lot about data mining and machine learning. I am extremely curious about machine learning, and I want to get introduced and get familiar to the different models that we are going to learn this semester.

**4.** [P] Print the Python version (available in sys package)

In [161]:
import sys
print(sys.version)

3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]


**5.** [P] Create a Python list of 10000 random integers in the range 1 to 100 using the random package. Name the
list x_list.

In [162]:
import random
x_list = []
for i in range(10000):
    x_list.append(random.randint(1, 100))

print(x_list)

[12, 76, 48, 85, 22, 74, 36, 65, 53, 44, 19, 41, 5, 44, 61, 24, 34, 55, 78, 96, 15, 57, 74, 46, 9, 75, 10, 1, 59, 21, 44, 43, 65, 16, 16, 88, 2, 30, 51, 94, 84, 83, 23, 71, 26, 16, 37, 88, 65, 64, 88, 78, 89, 89, 40, 12, 41, 23, 42, 55, 55, 66, 1, 42, 38, 62, 70, 31, 44, 19, 15, 9, 69, 69, 25, 57, 25, 46, 52, 24, 13, 57, 87, 73, 72, 12, 91, 76, 64, 70, 51, 28, 2, 14, 45, 79, 34, 54, 78, 48, 67, 97, 2, 58, 95, 5, 34, 86, 55, 2, 8, 19, 57, 58, 95, 58, 50, 79, 94, 4, 20, 88, 19, 33, 37, 85, 27, 77, 24, 73, 78, 66, 25, 18, 24, 96, 59, 42, 98, 20, 30, 41, 95, 57, 19, 6, 78, 75, 69, 65, 9, 22, 45, 28, 15, 67, 16, 20, 98, 99, 6, 51, 6, 61, 55, 5, 88, 85, 10, 16, 36, 24, 78, 90, 25, 55, 31, 62, 73, 43, 14, 63, 14, 6, 24, 88, 71, 25, 53, 91, 86, 78, 38, 9, 47, 82, 33, 52, 54, 9, 4, 46, 6, 62, 38, 32, 6, 69, 21, 17, 85, 45, 20, 33, 97, 7, 42, 57, 69, 20, 7, 27, 94, 21, 29, 11, 93, 63, 88, 66, 5, 21, 81, 94, 48, 91, 33, 85, 56, 19, 62, 24, 11, 38, 70, 39, 30, 17, 91, 40, 22, 23, 68, 92, 21, 97, 2

**6.** [P] What is the minimum value of x_list? What is the max value? What is the mode?

In [163]:
import statistics

print("minimum value of x_list: " + str(min(x_list)))
print("maximum value of x_list: " + str(max(x_list)))
print("mode of x_list: " + str(statistics.mode(x_list)))

minimum value of x_list: 1
maximum value of x_list: 100
mode of x_list: 61


**7.** [P] Write a function to take a list of numbers as a parameter, and return the average of the list. Then, use your function to report the average value of x_list, printed as a float with 2 places of precision.

In [164]:
def average_list(li):
    average = statistics.mean(li)
    return average

print("{:.2f}".format(average_list(x_list)))

50.46


**8.** [P] Create a list called x_hist that represents a histogram, i.e. a distribution of the numerical data, of x_list. Each entry in x_hist should contain the frequency of data over a bin width of 10. So, for example, x_hist[0] represents the frequency of numbers between 1-10, x_hist[1] is the frequency of numbers between 11-20, and so on. Be sure to print x_hist at the end. (Do NOT use numpy!)

In [165]:
x_hist = [0] * 10

for i in x_list:
    x_hist[(i-1) // 10] += 1

print(x_hist)

[1008, 1006, 975, 1037, 981, 978, 1042, 969, 979, 1025]


**9.** [M] What is numpy? What are its strengths? Does it have any weaknesses?

I asked ChatGPT, but these are my own words:
Numpy is a Python library that offers various tools to perform operations on matrices of data. It also provides a multidimensional array object. It supports vectorized operation, broadcasting, and indexing and slicing. It is strong in data analysis and machine learning.
Numpy has weaknesses. It has little support for non-numerical values. Numpy arrays also only hold values of the same type. It does not support object-oriented programming, and it does not have the most efficient memory allocation compared to other packages.

**10.** [P] Import the numpy package as np and print the numpy version

In [166]:
import numpy as np
print(np.__version__) # from ChatGPT

1.23.5


**11.** [M] What is the primary object type in numpy? Can it store data of different types? Discuss.

ndarray is the primary object type. It cannot store data of different types. We have the option to define the specific type of the values that it stores when we are creating it.

**12.** [M] Discuss the types of data available in numpy. You need not list every type. Just generalize, and discuss how the type system is different than the built-in types int and float in Python.

There are signed and unsigned 'int', 'ufloat', and others that the user can specify the number of bits that they take. For example, 'int32'. There are also boolean, object, and fixed length string. Numpy's data types have specific lengths, making them more memory efficient. Some of Numpy's data types can also specify whether they are signed or unsigned.

**13.** [P] Research how to use numpy to compute the same result as problem 8 above. (HINT: np.histogram)

In [167]:
x_hist, bin_edges = np.histogram(x_list)
x_hist

array([1008, 1006,  975, 1037,  981,  978, 1042,  969,  979, 1025],
      dtype=int64)

**14.** [P] Create a numpy array from x_list. Reassign it as x_list. Show the contents of the first 20 entries.

In [168]:
x_list = np.array(x_list)
x_list[:20]

array([12, 76, 48, 85, 22, 74, 36, 65, 53, 44, 19, 41,  5, 44, 61, 24, 34,
       55, 78, 96])

**15.** [P] Redo the previous exercise, but set the data type of each value to 'float32'

In [169]:
x_list = x_list.astype(np.float32)
x_list[:20]

array([12., 76., 48., 85., 22., 74., 36., 65., 53., 44., 19., 41.,  5.,
       44., 61., 24., 34., 55., 78., 96.], dtype=float32)

**16.** [P] Create a length 10 integer array filled with zeros

In [170]:
int_array = np.zeros(10, dtype=int)
int_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**17.** [P] Create a float array of 3 rows and 4 columns, all initialized to one.

In [171]:
float_array = np.ones((3, 4), dtype=float)
float_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**18.** [P] Create an array of 20 values, evenly spaced between 1 and 3 (HINT – look at np.linspace)

In [172]:
even_array = np.linspace(1, 3, 20)
even_array

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

**19.** [P] Set the numpy random seed to the value 12345, then create a 10 x 5 array of random integers on the interval [10, 50), assigned to x_mat

In [173]:
np.random.seed(12345)
x_mat = np.random.randint(low=10, high=50, size=(10,5))
x_mat

array([[44, 47, 39, 11, 46],
       [47, 44, 39, 11, 24],
       [37, 26, 19, 21, 23],
       [20, 27, 28, 48, 17],
       [49, 33, 39, 41, 43],
       [37, 33, 46, 10, 13],
       [15, 25, 21, 24, 27],
       [15, 44, 18, 15, 44],
       [15, 29, 22, 24, 26],
       [37, 48, 34, 42, 15]])

**20.** [P] Use slicing to select and show the first and last row of x_mat

In [174]:
# ChatGPT
x_mat[np.r_[0,-1],:]

array([[44, 47, 39, 11, 46],
       [37, 48, 34, 42, 15]])

**21.** [P] Now, show the first, third and fifth column of x_mat

In [175]:
# ChatGPT
x_mat[:, [0, 2, 4]]

array([[44, 39, 46],
       [47, 39, 24],
       [37, 19, 23],
       [20, 28, 17],
       [49, 39, 43],
       [37, 46, 13],
       [15, 21, 27],
       [15, 18, 44],
       [15, 22, 26],
       [37, 34, 15]])

**22.** [P] Show the sum of each row.

In [176]:
sums = np.sum(x_mat, axis=1)
sums

array([187, 165, 126, 140, 205, 139, 112, 136, 116, 176])