# Lab02 - numpy

Name: Jimmy (Qixiao) Zhu
Class: CSCI 349 - Intro to Data Mining
Semester: 2023SP
Instructor: Brian King

In [33]:
# Setting things up
import sys
import numpy as np
print(sys.version)
print("numpy: " + str(np.__version__))

3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
numpy: 1.23.5


**1)** [P] Create a 100000 x 75 matrix of zeros, stored as X. Then, print out the shape of the matrix, the base data type, the individual item size in the array, and the total size of the array in bytes (as an integer). Also, print out the total size in megabytes with 3 significant digits.

In [34]:
X = np.zeros((100000, 75))
print("Shape: " + str(X.shape))
print("Data type: " + str(X.dtype))
print("Individual Item size: " + str(X.itemsize) + " bytes")
print("Total size: " + str(X.nbytes) + " bytes")
print("Total size: {:.3f} megabytes".format(X.nbytes / (1024 * 1024)))


Shape: (100000, 75)
Data type: float64
Individual Item size: 8 bytes
Total size: 60000000 bytes
Total size: 57.220 megabytes


**2)** [P] Resize X to have the same number of elements, but with 100 columns. Show the shape. Show the number of bytes (which should be the same as the previous answer)

In [35]:
X = X.reshape((-1, 100))
print("Shape: " + str(X.shape))
print("Number of bytes: " + str(X.nbytes) + " bytes")

Shape: (75000, 100)
Number of bytes: 60000000 bytes


**3)** [P] Redo #1, but use a base datatype of 16-bit integers.

In [36]:
X = np.zeros((100000, 75), dtype=np.int16)
print("Shape: " + str(X.shape))
print("Data type: " + str(X.dtype))
print("Individual Item size: " + str(X.itemsize) + " bytes")
print("Total size: " + str(X.nbytes) + " bytes")
print("Total size: {:.3f} megabytes".format(X.nbytes / (1024 * 1024)))

Shape: (100000, 75)
Data type: int16
Individual Item size: 2 bytes
Total size: 15000000 bytes
Total size: 14.305 megabytes


**4)** [P] How many dimensions does X have? Answer using the appropriate property of np.ndarray objects.

In [37]:
X.ndim

2

**5)** [P] Enter the following Python list in your cell:
str_nums = ['2.14', '-9.300', '42']
Convert this to a numpy array named X. What is the base type? Show the contents of X.
We want numeric representation. So, convert X to an array of single precision floating point numbers. (HINT: use astype). Show X again.

In [38]:
str_nums = ['2.14', '-9.300', '42']
X = np.array(str_nums)
print("Base type: " + str(X.dtype))
print(X)
X = X.astype(np.float32)
print(X)

Base type: <U6
['2.14' '-9.300' '42']
[ 2.14 -9.3  42.  ]


**6)** [P] Copy the three definitions above for the Python lists days, scores_1, and scores_2. Create a numpy array called scores that has scores_1 as the first row and scores_2 as the second row using np.concatenate. Then, change days into a np.array from the list days. Show the contents of scores and days, and output their shape.

In [39]:
days = ["Mon","Tue","Wed","Thu","Fri"]
scores_1 = [9.5, 8.75, 8, 10, 7.75]
scores_2 = [9, 8, 9.5, 8.75, 7.25]

scores_1 = np.array(scores_1)[np.newaxis, :]
scores_2 = np.array(scores_2)[np.newaxis, :]

scores = np.concatenate((scores_1, scores_2), axis=0)
days = np.array(days)

print("scores:")
print(scores)
print("scores shape: " + str(scores.shape) + "\n")
print("days:")
print(days)
print("days shape: " + str(days.shape))

scores:
[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.    9.5   8.75  7.25]]
scores shape: (2, 5)

days:
['Mon' 'Tue' 'Wed' 'Thu' 'Fri']
days shape: (5,)


**7)** [P] Repeat the previous problem with the creation of scores from the Python lists scores_1 and
scores_2, but now do it with np.vstack. The array should be identical.

In [40]:
scores = np.vstack((scores_1, scores_2))
scores

array([[ 9.5 ,  8.75,  8.  , 10.  ,  7.75],
       [ 9.  ,  8.  ,  9.5 ,  8.75,  7.25]])

**8)** [P/M] Compare the result of the expression days == "Fri" if the variable days was a Python list as
entered above, vs. days being a numpy array. What is the difference in the result? In general, how does
numpy deal with standard comparison operators?

In [41]:
days = days.tolist()
print(days == "Fri")

days = np.array(days)
print(days == "Fri")

False
[False False False False  True]


Python is only comparing if the list "days" is the same as the string "Fri". They are not of the same type, so Python outputs False. Numpy, on the other hand, compares every element of the list "days" to "Fri" and lets us see if each element is the same as "Fri". In general, numpy compares every element of the array on the left of "==" with the thing on the right.

**9)** [P] The scores array represents quizzes that are out of 10 pts. Show the scores array scaled to be out of 100
pts (but do not change scores itself.)

In [42]:
scores_100 = scores * 10
scores_100

array([[ 95. ,  87.5,  80. , 100. ,  77.5],
       [ 90. ,  80. ,  95. ,  87.5,  72.5]])

**10)** [P] Select the scores that fell on Tuesday.

In [43]:
is_Tue = (days == "Tue")
scores[:, is_Tue]

array([[8.75],
       [8.  ]])

**11)** [P] Select all of the scores that are NOT on Tuesday (Hint – look up the ~ operator)

In [44]:
scores[:, ~is_Tue]

array([[ 9.5 ,  8.  , 10.  ,  7.75],
       [ 9.  ,  9.5 ,  8.75,  7.25]])

**12)** [P] Select the scores that were on Tuesday or Thursday

In [45]:
# ChatGPT
is_tue_or_thu = np.isin(days, ["Tue", "Thu"])
scores[:, is_tue_or_thu]

array([[ 8.75, 10.  ],
       [ 8.  ,  8.75]])

**13)** [P] Show the minimum and maximum scores for the entire array of scores

In [46]:
print("min = " + str(scores.min()))
print("max = " + str(scores.max()))

min = 7.25
max = 10.0


**14)** [P] Show the maximum scores for each week as a new array. The result should have the same dimensions (hint
– use the keepdims parameter of np.max).

In [47]:
scores.max(axis=1, keepdims=True)

array([[10. ],
       [ 9.5]])

**15)** [P] Report the day that the maximum score occurred each week. (HINT: use argmax and use that result to
index days.)

In [48]:
max_score_by_week = np.argmax(scores, axis=1)
days[max_score_by_week]

array(['Thu', 'Wed'], dtype='<U3')

**16)** [P] Report the mean of the scores of each week

In [49]:
scores.mean(axis=1)

array([8.8, 8.5])

**17)** [P] Suppose the lowest score was dropped from each week. Report the mean of each week, but without the
minimum score for that week.

In [50]:
no_min_by_week = np.delete(scores, scores.argmin(axis=1), axis=1)
no_min_by_week.mean(axis=1)

array([9.0625, 8.8125])

**18)** [P] Show the number of scores that were > 9 each week as an array.

In [51]:
greater_9 = scores > 9
greater_9.sum(axis=1)

array([2, 1])

In [52]:
np.random.seed(1234)
X = np.random.randint(1,100,50).reshape((10,5))
X

array([[48, 84, 39, 54, 77],
       [25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59],
       [93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39],
       [68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66],
       [76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14],
       [97, 13, 70, 96, 32]])

**19)** [P] Select the first row of X

In [53]:
X[0, :]

array([48, 84, 39, 54, 77])

**20)** [P] Select the last column of X

In [54]:
X[:, -1]

array([77, 27, 59, 48, 39, 81, 66, 61, 14, 32])

**21)** [P] Select the first AND last column of X

In [55]:
X[:, (0, -1)]

array([[48, 77],
       [25, 27],
       [31, 59],
       [93, 48],
       [51, 39],
       [68, 81],
       [ 4, 66],
       [76, 61],
       [47, 14],
       [97, 32]])

**22)** [P] Select every other row of X

In [56]:
X[::2]

array([[48, 84, 39, 54, 77],
       [31, 44, 31, 27, 59],
       [51, 77, 38, 35, 39],
       [ 4,  3, 20, 13, 66],
       [47, 29, 82, 88, 14]])

**23)** [P] Show the transpose of X, but don't change X itself

In [57]:
np.transpose(X)

array([[48, 25, 31, 93, 51, 68,  4, 76, 47, 97],
       [84, 16, 44, 70, 77, 12,  3, 82, 29, 13],
       [39, 50, 31, 81, 38,  1, 20, 15, 82, 70],
       [54, 24, 27, 74, 35, 76, 13, 72, 88, 96],
       [77, 27, 59, 48, 39, 81, 66, 61, 14, 32]])

**24)** [P] Select the first column of X and set the result to new variable Y.

In [58]:
Y = X[:, 0]
Y

array([48, 25, 31, 93, 51, 68,  4, 76, 47, 97])

**25)** [P] Increment the first value of Y, then show the corresponding value of X. Did both values in X and Y change?
THIS IS AN IMPORTANT OBSERVATION WHEN DEALING WITH SELECTING DATA!

In [59]:
Y[0] += 1
print("Y[0] = " + str(Y[0]))
print("X[0, 0] = " + str(X[0, 0]))
print("Both Y[0] and corresponding X[0, 0] incremented by 1.")

Y[0] = 49
X[0, 0] = 49
Both Y[0] and corresponding X[0, 0] incremented by 1.


**26)** [P] Repeat exercise 24, but ensure that Y is assigned a copy of the selected data. Increment the first value of Y
again and ensure that the corresponding value of X did not change.

In [60]:
Y = np.copy(X[:, 0])
Y[0] += 1
print("Y[0] = " + str(Y[0]))
print("X[0, 0] = " + str(X[0, 0]))

Y[0] = 50
X[0, 0] = 49


**27)** [P] Create an array that contains the sequence of numbers 0, 0.1, 0.2, … 9.8, 9.9 using arange, as a 10x10
matrix, stored as X. (HINT: Use np.arange)

In [61]:
X = np.arange(0, 10, 0.1).reshape((10, 10))
X

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

**28)** [P] Set the RNG seed to 1234. Then create an array X of 100 uniformly distributed numbers, with all values
between 1.0 and 10.0. Then, show the mean, the median, the minimum and maximum values of X.

In [62]:
np.random.seed(1234)
X = np.random.uniform(1.0, 10.0, [100])
print("first ten elements of X: " + str(X[0 : 10]))
print("mean = " + str(X.mean()))
print("median = " + str(np.median(X)))
print("minimum = " + str(X.min()))
print("maximum = " + str(X.max()))

first ten elements of X: [2.72367505 6.59897894 4.93954965 8.06822725 8.01978227 3.45333345
 3.4881783  8.2168496  9.62325418 8.88339371]
mean = 5.665266170909222
median = 5.827284349552116
minimum = 1.0558766492841647
maximum = 9.928733195695253


**29)** [M] Define what is meant by a normal distribution. What are the parameters of a normal distribution?

Searched on ChatGTP:
A normal distribution describes the probability density function of a continuous probability distribution. The graph is symmetrical bell-shaped, with the majority of the data distributed in the middle. The mean, median, and mode of the distribution are very close, if not the same. The mean and the standard deviation are the two parameters of a normal distribution.

**30)** [M] In simple terms, using a normal distribution, what does the Law of Large Numbers tell us?

ChatGPT:
The law of large numbers and the central limit theorem together tell us that as the sample size increases, the sample mean will be a good estimate of the population mean, and will be approximately normally distributed, even if the underlying data is not.

**31)** [P] Write a function called test_normal_dist. The purpose of this function is to evaluate the law of large numbers. It should have four parameters:
mu = mean of distribution
sd = standard deviation
vec_length = length of the vector to generate randomly from a normal distribution, with mu and sd as parameters
num_trials = number of times to repeat the experiment
The function should behave as follows. First, initialize the seed value to 1234, before your loop. Then, loop for num_trials, generating vec_length numbers from a normal distribution. Compute the mean of that vector, then compute its deviation (absolute value of the observed mean - expected mean). This should be repeated for all trials. Return the average of this deviation over all trials.

In [63]:
def test_normal_dist(mu, sd, vec_length, num_trials):
    np.random.seed(1234)
    deviation = 0

    for i in range(num_trials):
        vector = np.random.normal(mu, sd, vec_length)
        mean = vector.mean()
        deviation += abs(mean - mu)

    return deviation / num_trials

**32)** [P] Use test_normal_dist to obtain the deviation for vector lengths of 10, 100, 1000, 10000, and 100000. Use a fixed number of trials of 100 for each experiment. Report the results as a numpy array with two dimensions. the first being the vector length, and the second being the average deviation resulting from your test_normal_dist function.

In [64]:
vec_length = 1

lengths = np.array([10, 100, 1000, 10000, 100000])
averages = np.zeros(5)

while vec_length < 100000:
    vec_length *= 10
    averages[vec_length == lengths] = test_normal_dist(10, 2, vec_length, 100)

np.vstack((lengths, averages))

array([[1.00000000e+01, 1.00000000e+02, 1.00000000e+03, 1.00000000e+04,
        1.00000000e+05],
       [4.77240837e-01, 1.61925065e-01, 4.45800014e-02, 1.58883885e-02,
        4.88701220e-03]])